POST http://localhost:5000/print-barcode-labels HTTP/1.0
Content-Type: application/json
Content-Length: 204

{
  "vid":  "0x6ef0",
  "pid": "0x6550",
  "sizeX": 55,
  "sizeY": 45,
  "direction": 0,
  "topText": "100tk",
  "barcodeData": "AX2B2CL21LL2",
  "printCount": 2
}

